version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
  - dependency-name: "@fullhuman/postcss-purgecss"
    versions:
    - 3.1.3
    - 4.0.0
