title: Jamstatic
baseline: Sites statiques et architectures découplées
baseurl: https://jamstatic.fr/
description: Jamstatic, la communauté des sites statiques et des architectures découplées.
author:
  name: Jamstatic
  url: https://jamstatic.fr
image: images/twitter-card.png
language: fr
languages:
  - code: fr
    locale: fr
podcast:
  title: Génération Statique
  url: https://anchor.fm/jamstatic
#
pagination:
  enabled: false
paths:
  - section: post
    path: :year/:month/:day/:slug
body:
  images:
    responsive:
      enabled: true
    webp:
      enabled: true
    caption:
      enabled: true
    remote:
      fallback:
        enabled: true
        path: images/no-image.png
  links:
    embed:
      enabled: true
output:
  formats:
    - name: atom
      mediatype: application/atom+xml
      filename: index
      extension: xml
      exclude: [redirect, paginated]

#email: contact@jamstatic.fr
#author:
#  name: Frank Taillandier
#  url: https://frank.taillandier.me
#  avatar: https://github.com/DirtyF.png
#  GitHub: DirtyF
#social:
#  twitter: jamstatic_fr
#  GitHub: jamstatic
#podcast:
#  url: https://anchor.fm/jamstatic
#  title: Génération Statique
#cloudinary: https://res.cloudinary.com/jamstatic/image/upload
#opencollective: https://opencollective.com/jamstatic
#ghrepo: https://github.com/jamstatic/jamstatic-fr/
#branch: master
#rssPodcast: https://anchor.fm/s/39f4fa04/podcast/rss
